add_sb_package(NAME Qt4 GROUPS GRAPHICS VERSION 4.7.2 DEFAULT SYSTEM)

if (SB_USE_SYSTEM_QT4)
  if (NOT DEFINED QT_QTOPENGL_INCLUDE_DIR)
    message(FATAL_ERROR "QT_QTOPENGL_INCLUDE_DIR is not set but required")
  endif()
endif()

